SELECT TOP (1000) [ID]
      ,[MONGOID]
      ,[Username]
      ,[UserPassKey]
      ,[SavedDataId]
      ,[EmailAddress]
      ,[Otp]
      ,[CodeGenerateTime]
      ,[IsVerified]
      ,[Salt]
  FROM [sparklmo_userData].[sparklmo_admin].[UserData]